// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfQ_i6hvH66n0J-zV7hP3N9GinaP0UPIo',
    appId: '1:843516902022:web:cbdf87cf9ce8644f67af07',
    messagingSenderId: '843516902022',
    projectId: 'final-lift-app-bc93b',
    authDomain: 'final-lift-app-bc93b.firebaseapp.com',
    storageBucket: 'final-lift-app-bc93b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBR5c8Gg2iswhFbUUXg-gQxaYfQBc1uRQ',
    appId: '1:843516902022:android:427b6e3c2941d79867af07',
    messagingSenderId: '843516902022',
    projectId: 'final-lift-app-bc93b',
    storageBucket: 'final-lift-app-bc93b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjBIGe-eNbpihSN7eDr1uIqyqxlaebsqQ',
    appId: '1:843516902022:ios:45c2599e4ecf471067af07',
    messagingSenderId: '843516902022',
    projectId: 'final-lift-app-bc93b',
    storageBucket: 'final-lift-app-bc93b.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjBIGe-eNbpihSN7eDr1uIqyqxlaebsqQ',
    appId: '1:843516902022:ios:45c2599e4ecf471067af07',
    messagingSenderId: '843516902022',
    projectId: 'final-lift-app-bc93b',
    storageBucket: 'final-lift-app-bc93b.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
